### PR TITLE
Use safestring.mark_safe on MultiForm methods which output html

### PR DESCRIPTION
**Pull request by frankier**

### CODE REVIEW

**Comment by pipermerriam** [comment]
Can you explain your reasoning behind this.  Seems like a massive cross site scripting attack vector.

**Comment by frankier** [comment]
The methods in Django's Form class these methods wrap use mark_safe too. The safestring we get from them is cast back to a normal string when we do "".join(). These methods are meant to output unescaped html. If we return an unsafe (normal) string then the interface of MultiForm is no longer exactly compatible with Django's Form.

**Comment by pipermerriam** [comment]
Enlightening and makes sense now that I look back on it.

**Comment by rockymeza** [comment]
oh. hey can we get some tests on this?

**Comment by rockymeza** [comment]
I realize now that I've never used the `as_(table|p|ul)` methods. We should have some tests to make sure they work.

**Pull request merged**
