### PR TITLE
Does not work with Django Form Wizard

### PR DESCRIPTION
**Pull request by rockymeza**
I've tried creating a MultiForm containing two regular forms, but I could not add that one to a regular Django WizardView. Is there another way to make this work?

### CODE REVIEW

**Comment by rockymeza** [comment]
Hi @dirkmoors,

Here's my attempt at getting this to work. Could you try it out?

**Comment by pipermerriam** [comment]
:+1:  on this.  Looks good @rockymeza

**Comment by frankier** [comment]
It looks like it should actually be possible to provide a reasonable implementation of base_fields, that would at least allow WizardView's introspection to work correctly. See: https://github.com/frankier/django-betterforms/commit/e1d1d0aeb9f4326733a57b49aa0adba4d1b3d547

If I merged this into this PR, and adjusted the docs accordingly, is there any interest in merging this?

**Comment by pipermerriam** [comment]
@frankier yes, if you want to get this PR updated I'll get it merged and released.

**Comment by pipermerriam** [comment]
@frankier  Actually, I'm going to merge this, and you can just PR in your change independently.

**Comment by rockymeza** [comment]
Hey @frankier,

thanks for all the interest in betterforms recently. I would love to see your PR get merged, the only thing I want is to have a big stinking warning in the docs about how base_fields is an approximation.

**Pull request merged**
