### PR TITLE
Django 3.0 support

### PR DESCRIPTION
**Pull request by jpic**

### CODE REVIEW

**Comment by edderleonardo** [comment]
support for django 3?, interesting

**Comment by jpic** [comment]
@edderleonardo available in PyPi package  django-betterforms-jpic meanwhile it's released in the official package

**Comment by abdelba** [comment]
@jpic why is this not merged yet and released ?

**Comment by vapavlov** [comment]
It is really weird: this simple but important patch is more than 2 years old, but still not merged... 

P.S. Thanks to @jpic for a working fork of this package for Django 3.

**Comment by CSprat451** [comment]
Closed in favor of #68

**Pull request closed without merging**
