### PR TITLE
[WIP] Begin adding Django 1.8 support

### PR DESCRIPTION
**Pull request by frankier**
Some tests fail. It looks like there is a genuine problem with BetterForm.

### CODE REVIEW

**Comment by rockymeza** [comment]
@acatton @pipermerriam, is travis not running the tox tests? we should probably get that working so that we don't have this duplication.

**Comment by rockymeza** [comment]
I don't know how I feel about the travis_gen file in the repo, but let's leave it for now.

https://docs.djangoproject.com/en/dev/releases/1.8/#forms states that they add the `required_css_class` to labels.

I believe our policy regarding changes like this in Django's behavior is to try to update django-betterforms to match Django's new behavior in all versions, if possible. So ideally, we would be rendering labels with the `require_css_class` in them as well. That's the only failure I see in Django 1.8 tests.

There is another failure in django 1.4's tests, but that might be because of a limitation of Django 1.4's `assertHTMLEqual` implementation:

```diff
- <fieldset class="first formFieldset">
?                  ------
+ <fieldset class="formFieldset first">
?                              ++++++
```

I'm willing to let this PR through despite the 1.4 test failures, especially if we're dropping support for < 1.7 anyway.

**Comment by frankier** [comment]
Okay, well now the tests pass for Django 1.7 and 1.8 only. Should I just merge #29 into this PR so we make a clean break from supporting 1.4 and partially 1.8 to fully supporting only 1.8 and 1.7?

**Comment by CSprat451** [comment]
Closed in favor of #68

**Pull request closed without merging**
